version: '2'
services:
  reverse_proxy:
    image: nginx-rp:latest
    volumes:
     - ./nginx-config/basic-rp/:/etc/nginx/default.d/:ro
     - ./nginx-config/conf.d/:/etc/nginx/conf.d/:ro
     - ./nginx-config/keys/:/etc/nginx/ssl/:ro
    ports:
     - "443:443"
    environment:
     - NGINX_PORT=443
    command: >
        /bin/bash -c "sed -e s/80/443/g -i /etc/nginx/nginx.conf
        && grep 443 /etc/nginx/nginx.conf
        && nginx -g 'daemon off;'"
